sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - $HOME/.conan

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
        key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - clang-3.8
      - cmake
      - cmake-data

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  
osx_image: xcode8

env:
  - build_type=debug options="-D stlab_testing=ON"
  - build_type=release options="-D stlab_testing=ON"

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        build_type=debug
        coverage=TRUE
        options="-D stlab_testing=ON -D coverage=ON"
      packages:
        - lcov
      after_success:
        - cd build
        - bash <(curl -s https://codecov.io/bash) -X fix

    - os: linux
      compiler: clang
      env:
        build_type=debug
        flags="-fsanitize=address;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"
        
    - os: linux
      compiler: clang
      env:
        build_type=debug
        flags="-fsanitize=undefined;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"
        
    - os: linux
      compiler: clang
      env:
        build_type=debug
        TSAN_OPTIONS="suppressions=${TRAVIS_BUILD_DIR}/test/sanitizer_suppressions"
        flags="-fsanitize=thread;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"

    - os: linux
      compiler: clang
      env:
        build_type=debug
        options="-D stlab_testing=ON"
      before_install:
        - pip install conan
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      addons:
        apt:
          sources:
            - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
              key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
            - ubuntu-toolchain-r-test
            - george-edison55-precise-backports
          packages:
            - g++-5
            - clang-3.8
            - cmake
            - cmake-data
        coverity_scan:
          project:
            name: "stlab/libraries"
            description: "Build submitted via Travis CI"
          notification_email: fosterb@gmail.com
          build_command_prepend: ""
          build_command: ".travis/build.sh"
          branch_pattern: coverity

  exclude:
    - os: osx
      compiler: gcc

branches:
  except: /pr\/.*/
  
before_install:
  - pip install conan
  
script:
  - .travis/build.sh
  
notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: osabC069BWFmRWN9PrcG13G0fq3/FM1OJA5iZuPuj0rbsZfhObG1zX0M5ArjhniLh/E1X1Pay7W55x8aUhOxVjx8JkSNRRpRWKFVLnqB6JrVtL/nZUNNz5PlRViAW3beV8E/kxS923dOqY4tTQeFFHyrMO5zNpLpAD5M/5pFveLCe6zBJaQUn5X4cL1V2fe6FWMIuZrChQLXp+eO6HB4ZyJnz1P8RMMTXDhNuEal5CXsNO0pA/f73s8Q8I41yHH9QbDwH2rgCdY8Qh+zeOLNHAq5uZNn7ODvJGul9rQvHKU539/EbvVjEPaOHgdXp0DNX/AI/63mAmDo6Zeb0b9fj9DwyN7dWxAM/s4EP5nfeyRor+xp/nJCKZr4D4xIxE/tZk4GPbhX1yi2Vs8zcuf78sFKWcPKzaSndyJfffrevGK0lWukkQEnaAyWQ1yj1ArEyvrovk8xQZv52FJ2doVfd3OWKCClMG3WUITyM9viBRQE/06abf45Gyswpn0Njwsj0ZnlcBn/Im0qTItk19xYI1zO8fdxLnTRYCRHE3CbrP6v30NP3RZtjz2M6oRONi00GL2xOKVghPYIQG2HoQa0AAd3CFu1/tR6y+POEp97yJhBlVuGNvwZv+OM2ZcIlh3byw00oxlWyE3Xdwx3yad17m513i1sMGnoE69dmzNVLU0=
