sudo: required
dist: trusty
language: cpp

cache:
  directories:
    - $HOME/.conan

addons:
  apt:
    sources:
      - sourceline: "deb http://apt.llvm.org/precise/ llvm-toolchain-precise-3.8 main"
        key_url : "http://apt.llvm.org/llvm-snapshot.gpg.key"
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports
    packages:
      - g++-5
      - clang-3.8
      - cmake
      - cmake-data

compiler:
  - gcc
  - clang

os:
  - linux
  - osx
  
osx_image: xcode8

env:
  - build_type=debug options="-D stlab_testing=ON"
  - build_type=release options="-D stlab_testing=ON"

matrix:
  include:
    - os: linux
      compiler: gcc
      env:
        build_type=debug
        coverage=TRUE
        options="-D stlab_testing=ON -D coverage=ON"
      packages:
        - lcov
        
    - os: linux
      compiler: clang
      env:
        build_type=debug
        flags="-fsanitize=address;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"
        
    - os: linux
      compiler: clang
      env:
        build_type=debug
        flags="-fsanitize=undefined;-fno-omit-frame-pointer;"
        options="-D stlab_testing=ON"
        
    # - os: linux
    #   compiler: clang
    #   env:
    #     build_type=debug
    #     flags="-fsanitize=thread;-fno-omit-frame-pointer;"
    #     options="-D stlab_testing=ON"   

    - os: linux
      branches:
        only:
          coverity
      before_install:
        - pip install conan
        - echo -n | openssl s_client -connect scan.coverity.com:443 | sed -ne '/-BEGIN CERTIFICATE-/,/-END CERTIFICATE-/p' | sudo tee -a /etc/ssl/certs/ca-
      compiler: clang
      env:
        - global:
          - secure: "oIVYGAAYk2xz2JTsYFMwPhkzZ6s1Uf0lu7xByr/FuaTunoY3PfxCk65gpgpVHiG/AT4zMjErehWihxEeL87nLOvgvVaBc1DuL6SLrWM/mFPgs+3gzwb9wWjEGXwbMq53KHyuDikcRnSH8aiGts1a3DvE7uLSlq585SlV9x++PwlXOnsnMosrq+vG7MLxy4ZeSyuEy/eo90xitVuXs8It+zYDVMOAoUaOMifd5mv5cEzCPMJBnzy/4Eiu2tkhi9F8Mc5H12nHN5IBGDfgJoInMNVmHTtXoFMdH28JqoL92ZZPuIkj2adxK+N19fcUoS2zqgZXMIz3Xi1iJSAR98yaNyLyoOQi7RHOYaW5FU3vFxAXHP0cfLXZyn8hJ2HruY8FSntlLs6polIv9npgZqv/bywVU5MrHbpmqPhlnzmtby0plCxUDYNK65hyR0KzUdcUW8J6UkDiC43tCfzcepmA5rulm86fXofUTKZT/13Ek6SSxOKnshBbggXU1m+UVEIM4A/Ln4VPUXdLYcbyMSF5Cu2SLgVq56kn7e8sF3EK1CBlN/3Lryat9cqtzHG7iSativSiORMROvkaHB1aQF+67VtwLOi4qdAMpBvphy3lGsxUUvdiAvu3L7eONcvEhAHMqIecMeKrS7rvvAukX4zydh46/wgQpDeKUotZNi3Tlmc="
        - build_type=debug
        - flags="-fno-omit-frame-pointer;"
        - options="-D stlab_testing=ON"
      addons:
        coverity_scan:
          project:
            name: "stlab/libraries"
            description: "Build submitted via Travis CI"
          notification_email: fosterb@gmail.com
          build_command_prepend: ""
          build_command: ".travis/build.sh"
          branch_pattern: coverity

  exclude:
    - os: osx
      compiler: gcc

branches:
  except: /pr\/.*/
  
before_install:
  - pip install conan
  
script:
  - .travis/build.sh
  
after_success:
  - cd build
  - bash <(curl -s https://codecov.io/bash) -X fix
  
notifications:
  recipients:
    - felix@petriconi.net
  email:
    on_success: change
    on_failure: always
  slack:
    on_success: change
    on_failure: always
    rooms:
      secure: D2Q2H8/89cCSDjJXc6AmIAOEKIkoUBQZBH5sYIkc/FgB7+cLqeSQFNpe7N96t22SmvyIUsqPzxiEccEMTiLeRdo0S4BXAAkd3abB8wd2KFXe/mlpUpNNSYTowYA6I6EfY83Hb5QxVkIi5SiD6fwUo9VFXGpBQM5wmgU9CXE4Xk64RWziSKowGSOzIPytSduksG2p+wKQE6tK0o4NNPvOI0uzbzJuWUwHjaLU/tH12L/O/DmeLj+WO1939v1Xmm48p86JKr7uJzNNiTTVCGuAMLY3CLdTRYHpgvnfAxy93x0v0arvYiRrtABlfUP1RjthUPlmY0oESIx1EbgSUMXx1Bh0tvfJoRUq2H2qu9V1mMhIrMj7JzWcLb+9X3+vWg7UPgz8Y2kX8PZbzxCclIqesWsgBbaqsErbS6o5Fh2hvTMzIjRXm8oXc38wbC3jM11H0CD7tCEvpUHyPHfVGYgf0/qFNSoFU3qhfuWRdhi3Pa+En9/VcFmDrbh2P9ba2kDqVnXzz2q+xRZ1rfmzBiKOe05TVTm4535JbcRPCa4bgE+gT6PvVIlb4WSJk6pZleAlo/lh8Ugqc4fCRiShhxd0lKK+3+B1ImipuVeaNaTGUgfhtj4hhMzXEp9Xi+M3UyScnXvQhLc7pA3eYO6paXuVjBUIzAWOXzsPVwCVPFoObhY=
